### PR TITLE
Introduce support for phpseclib3

### PR DESCRIPTION
**Pull request by N4M3Z**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
@CthulhuDen what is your thoughts on this? As for now any dependency to phpseclib 3 makes this ios-receipt-parser incompatible.

**Comment by CthulhuDen** [comment]
Hi all. Sorry for the delay. This PR is currently hard to review as it starts from my 1st commit, omitting next 3, and a lot of their content shows as difference. @N4M3Z If you could pull from my master that would certainly make it easier.

**Comment by N4M3Z** [comment]
It's based on your latest commit, just squashed to keep only relevant history.

**Comment by CthulhuDen** [comment]
Well I don't thinks that makes sense in the context of a PR because original history stays as is in this repo.

**Pull request closed without merging**
